#!/bin/bash

dracut_install ip 
inst dcbtool 
inst fipvlan
inst lldpad
inst vconfig
inst readlink

mkdir -p "$initdir/var/lib/lldpad"

inst "$moddir/fcoe-up" "/sbin/fcoe-up"
inst "$moddir/fcoe-edd.sh" "/sbin/fcoe-edd"
inst "$moddir/fcoe-genrules.sh" "/sbin/fcoe-genrules.sh"
inst_hook cmdline 99 "$moddir/parse-fcoe.sh"
