#!/bin/bash

modinfo -k $kernel dm_mod >/dev/null 2>&1 && \
    inst_hook pre-udev 30 "$moddir/dm-pre-udev.sh"

inst dmsetup

inst dmeventd

if ldd $(which dmraid) | grep -q lib64; then
    LIBDIR="/lib64"
else
    LIBDIR="/lib"
fi

for i in $(ls /{usr,}/$LIBDIR/libdmraid-events*.so 2>/dev/null); do
    dracut_install $i
done

inst_rules 10-dm.rules 95-dm-notify.rules
