#!/bin/bash
instmods iscsi_tcp iscsi_ibft crc32c
iscsi_module_test() {
    local iscsifuncs='iscsi_register_transport'
    fgrep -q "$iscsifuncs" "$1"
}
instmods $(filter_kernel_modules iscsi_module_test)

