#!/bin/bash
dracut_install umount
inst iscsistart 
inst hostname
inst iscsi-iname
type -P iscsiuio >/dev/null && inst iscsiuio
inst_hook cmdline 90 "$moddir/parse-iscsiroot.sh"
inst_hook pre-pivot 90 "$moddir/cleanup-iscsi.sh"
inst "$moddir/iscsiroot" "/sbin/iscsiroot"
inst "$moddir/mount-lun.sh" "/bin/mount-lun.sh"
